(define (problem cephalopod-instance)
  (:domain chephalopod_domain)
  (:objects
    cella-0-0 - cella
    cella-0-1 - cella
    cella-0-2 - cella
    cella-0-3 - cella
    cella-0-4 - cella
    cella-1-0 - cella
    cella-1-1 - cella
    cella-1-2 - cella
    cella-1-3 - cella
    cella-1-4 - cella
    cella-2-0 - cella
    cella-2-1 - cella
    cella-2-2 - cella
    cella-2-3 - cella
    cella-2-4 - cella
    cella-3-0 - cella
    cella-3-1 - cella
    cella-3-2 - cella
    cella-3-3 - cella
    cella-3-4 - cella
    cella-4-0 - cella
    cella-4-1 - cella
    cella-4-2 - cella
    cella-4-3 - cella
    cella-4-4 - cella
    human - giocatore
    ai - giocatore
    dado-umano-0 - dado
    dado-ai-0 - dado
    dado-umano-1 - dado
    dado-ai-1 - dado
    dado-umano-2 - dado
    dado-ai-2 - dado
    dado-umano-3 - dado
    dado-ai-3 - dado
    dado-umano-4 - dado
    dado-ai-4 - dado
    dado-umano-5 - dado
    dado-ai-5 - dado
    dado-umano-6 - dado
    dado-ai-6 - dado
    dado-umano-7 - dado
    dado-ai-7 - dado
    dado-umano-8 - dado
    dado-ai-8 - dado
    dado-umano-9 - dado
    dado-ai-9 - dado
    dado-umano-10 - dado
    dado-ai-10 - dado
    dado-umano-11 - dado
    dado-ai-11 - dado
    dado-umano-12 - dado
    dado-ai-12 - dado
    dado-umano-13 - dado
    dado-ai-13 - dado
    dado-umano-14 - dado
    dado-ai-14 - dado
    dado-umano-15 - dado
    dado-ai-15 - dado
    dado-umano-16 - dado
    dado-ai-16 - dado
    dado-umano-17 - dado
    dado-ai-17 - dado
    dado-umano-18 - dado
    dado-ai-18 - dado
    dado-umano-19 - dado
    dado-ai-19 - dado
    dado-umano-20 - dado
    dado-ai-20 - dado
    dado-umano-21 - dado
    dado-ai-21 - dado
    dado-umano-22 - dado
    dado-ai-22 - dado
    dado-umano-23 - dado
    dado-ai-23 - dado
    valore-1 - valore
    valore-2 - valore
    valore-3 - valore
    valore-4 - valore
    valore-5 - valore
    valore-6 - valore
  )
  (:init
    (not (occupata cella-0-0))
    (not (occupata cella-0-1))
    (not (occupata cella-0-2))
    (not (occupata cella-0-3))
    (not (occupata cella-0-4))
    (not (occupata cella-1-0))
    (not (occupata cella-1-1))
    (not (occupata cella-1-2))
    (not (occupata cella-1-3))
    (not (occupata cella-1-4))
    (not (occupata cella-2-0))
    (not (occupata cella-2-1))
    (not (occupata cella-2-2))
    (not (occupata cella-2-3))
    (not (occupata cella-2-4))
    (not (occupata cella-3-0))
    (not (occupata cella-3-1))
    (not (occupata cella-3-2))
    (not (occupata cella-3-3))
    (not (occupata cella-3-4))
    (not (occupata cella-4-0))
    (not (occupata cella-4-1))
    (not (occupata cella-4-2))
    (not (occupata cella-4-3))
    (not (occupata cella-4-4))
    (turno human)
  )
  (:goal (exists (?c - cella) (occupata ?c)))
)
